### ISSUE TITLE
Can't compile on ubuntu 18.04

### ISSUE THREAD

**Issue by jrgryph** [naev/naev#941]
My make output...

naev.c: In function ‘debug_translateAddress’:
naev.c:1364:12: warning: implicit declaration of function ‘bfd_section_flags’; did you mean ‘bfd_set_section_flags’? [-Wimplicit-function-declaration]
       if ((bfd_section_flags(section) & SEC_ALLOC) == 0)
            ^~~~~~~~~~~~~~~~~
            bfd_set_section_flags
naev.c:1367:44: error: macro "bfd_section_vma" requires 2 arguments, but only 1 given
       bfd_vma vma = bfd_section_vma(section);
                                            ^
naev.c:1367:21: error: ‘bfd_section_vma’ undeclared (first use in this function); did you mean ‘bfd_scan_vma’?
       bfd_vma vma = bfd_section_vma(section);
                     ^~~~~~~~~~~~~~~
                     bfd_scan_vma
naev.c:1367:21: note: each undeclared identifier is reported only once for each function it appears in
naev.c:1368:52: error: macro "bfd_section_size" requires 2 arguments, but only 1 given
       bfd_size_type size = bfd_section_size(section);
                                                    ^
naev.c:1368:28: error: ‘bfd_section_size’ undeclared (first use in this function); did you mean ‘bfd_section_vma’?
       bfd_size_type size = bfd_section_size(section);
                            ^~~~~~~~~~~~~~~~
                            bfd_section_vma
Makefile:1068: recipe for target 'naev.o' failed
make[3]: *** [naev.o] Error 1
Makefile:1106: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
Makefile:816: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:650: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by ids1024** [comment]
This seems to be the same as issue #925, which is fixed in the master branch.

You can build from git, or build with `--disable-debug` (which disables this and some other debugging support).

**Comment by jrgryph** [comment]
It worked... thanks!
